include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - build
  - scan

build:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - apk add --no-cache wget grep
    - VERSION=$(wget -qO- https://github.com/keybase/client/releases | grep -oP '(?<=releases\/tag\/)(.*?)(?=\">)' | awk 'NR==1{print $1}' | head -1)
  script:
    - cd Ubuntu/
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --label "com.jitesoft.app.keybase.verson=${VERSION}" --build-arg VERSION="${VERSION}" .
    - TAGS="latest ${VERSION}"
    - |
      for TAG in $TAGS; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${TAG}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} jitesoft/keybase:${TAG}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} quay.io/jitesoft/keybase:${TAG}
        docker push ${CI_REGISTRY_IMAGE}:${TAG}
        docker push jitesoft/keybase:${TAG}
        docker push quay.io/jitesoft/keybase:${TAG}
      done

build:alpine:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  variables:
    DOCKER_BUILDKIT: 1
  script:
    - cd Alpine/
    - HASH=$(wget -qO- https://github.com/keybase/client | tr -d '\n' | tr -d ' ' | grep -oP '(?<=commit-tease-sha).*[>]([\da-f]+)(?=<)' | grep -oP '(?<=\>)([\da-f]+)' | awk 'NR==1{print $1}')
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}/alpine" "latest,${HASH}")
#    - TAG_LIST="$(helper "itesoft/keybase" "latest-alpine,${HASH}-alpine") ${TAG_LIST}"
    - docker buildx build --platform "linux/amd64,linux/arm64" --build-arg KB_HASH="${HASH}" --progress plain --push ${TAG_LIST} .
  tags: [ jitesoft, arm64, amd64, buildx ]

scan:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"


scan:alpine:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/alpine:latest"
